export type ExtensionInput = {
  prompt: string;
  name: string;
  description: string;
  popupTitle: string;
  buttonText: string;
  primaryColor: string;
};

export type ExtensionFiles = Record<string, string>;

const escapeHtml = (value: string) =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;");

const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export function inferExtensionInput(prompt: string): ExtensionInput {
  const cleanPrompt = prompt.trim() || "Build a helpful productivity Chrome extension.";
  const lower = cleanPrompt.toLowerCase();
  const name = lower.includes("coupon")
    ? "Coupon Scout"
    : lower.includes("tab")
      ? "TabPilot"
      : lower.includes("focus") || lower.includes("productivity")
        ? "Focus Forge"
        : lower.includes("note")
          ? "Quick Notes"
          : "AI Chrome Assistant";

  const action = lower.includes("summar")
    ? "Summarize page"
    : lower.includes("coupon")
      ? "Find savings"
      : lower.includes("note")
        ? "Save note"
        : lower.includes("focus")
          ? "Start focus"
          : "Run assistant";

  return {
    prompt: cleanPrompt,
    name,
    description: `AI-generated extension: ${cleanPrompt.slice(0, 132)}${cleanPrompt.length > 132 ? "..." : ""}`,
    popupTitle: name,
    buttonText: action,
    primaryColor: "#2563eb"
  };
}

export function buildIconSvg(input: ExtensionInput, size = 128) {
  const initials = (input.name || "EF").split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 128 128">
  <defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="${input.primaryColor}"/><stop offset="1" stop-color="#7c3aed"/></linearGradient></defs>
  <rect width="128" height="128" rx="30" fill="url(#g)"/>
  <circle cx="96" cy="30" r="18" fill="white" opacity=".18"/>
  <text x="64" y="76" text-anchor="middle" font-family="Inter, Arial, sans-serif" font-size="40" font-weight="800" fill="white">${escapeHtml(initials)}</text>
</svg>`;
}

export function buildExtensionFiles(input: ExtensionInput): ExtensionFiles {
  const safeName = input.name || "My Extension";
  const safeDescription = input.description || "Generated by ExtensionForge";
  const safeTitle = input.popupTitle || safeName;
  const safeButton = input.buttonText || "Run extension";
  const color = input.primaryColor || "#2563eb";
  const slug = slugify(safeName) || "extensionforge-extension";

  return {
    "manifest.json": JSON.stringify({
      manifest_version: 3,
      name: safeName,
      description: safeDescription,
      version: "1.0.0",
      action: { default_popup: "popup.html", default_title: safeName, default_icon: { "16": "icons/icon-16.svg", "48": "icons/icon-48.svg", "128": "icons/icon-128.svg" } },
      background: { service_worker: "background.js" },
      content_scripts: [{ matches: ["<all_urls>"], js: ["content.js"], run_at: "document_idle" }],
      icons: { "16": "icons/icon-16.svg", "48": "icons/icon-48.svg", "128": "icons/icon-128.svg" },
      permissions: ["activeTab", "storage", "scripting"]
    }, null, 2),
    "popup.html": `<!doctype html>\n<html>\n  <head>\n    <meta charset="utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <title>${escapeHtml(safeTitle)}</title>\n    <link rel="stylesheet" href="styles.css" />\n  </head>\n  <body>\n    <main class="shell">\n      <p class="eyebrow">${escapeHtml(slug)}</p>\n      <h1>${escapeHtml(safeTitle)}</h1>\n      <p>${escapeHtml(safeDescription)}</p>\n      <button id="forge-action">${escapeHtml(safeButton)}</button>\n      <output id="forge-status">Ready.</output>\n    </main>\n    <script src="popup.js"></script>\n  </body>\n</html>`,
    "styles.css": `:root{color-scheme:dark;--brand:${color}}body{width:360px;margin:0;font-family:Inter,system-ui,sans-serif;background:#020617;color:white}.shell{padding:22px;background:radial-gradient(circle at top right,var(--brand),transparent 34%),linear-gradient(135deg,#020617,#111827)}.eyebrow{color:#bfdbfe;font-size:11px;letter-spacing:.12em;text-transform:uppercase}h1{font-size:26px;margin:8px 0}p{color:#cbd5e1;line-height:1.5}button{width:100%;border:0;border-radius:16px;background:white;color:#0f172a;padding:13px 16px;font-weight:800;cursor:pointer}output{display:block;margin-top:14px;color:#93c5fd}`,
    "popup.js": `const button = document.getElementById("forge-action");\nconst status = document.getElementById("forge-status");\nbutton.addEventListener("click", async () => {\n  status.textContent = "Working on the active tab...";\n  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });\n  await chrome.storage.local.set({ lastRun: new Date().toISOString(), extensionName: ${JSON.stringify(safeName)} });\n  status.textContent = tab?.title ? \`Applied to: \${tab.title}\` : "Action complete.";\n});\n`,
    "background.js": `chrome.runtime.onInstalled.addListener(() => {\n  chrome.storage.local.set({ installedAt: new Date().toISOString(), generatedBy: "ExtensionForge" });\n});\n`,
    "content.js": `(() => {\n  const marker = "${slug}-loaded";\n  if (document.documentElement.dataset[marker]) return;\n  document.documentElement.dataset[marker] = "true";\n  console.info("${safeName} content script is ready on", location.href);\n})();\n`,
    "icons/icon-16.svg": buildIconSvg(input, 16),
    "icons/icon-48.svg": buildIconSvg(input, 48),
    "icons/icon-128.svg": buildIconSvg(input, 128),
    "README.md": `# ${safeName}\n\n${safeDescription}\n\n## Load in Chrome\n\n1. Open chrome://extensions.\n2. Enable Developer mode.\n3. Select Load unpacked and choose this folder.\n\nGenerated by ExtensionForge from: ${input.prompt}\n`
  };
}
