export type ExtensionInput = { name: string; description: string; popupTitle: string; buttonText: string };

export function buildExtensionFiles(input: ExtensionInput) {
  const safeName = input.name || "My Extension";
  return {
    "manifest.json": JSON.stringify({ manifest_version: 3, name: safeName, description: input.description || "Generated by ExtensionForge", version: "1.0.0", action: { default_popup: "popup.html", default_title: safeName }, permissions: [] }, null, 2),
    "popup.html": `<!doctype html>\n<html>\n  <head>\n    <meta charset="utf-8" />\n    <title>${input.popupTitle || safeName}</title>\n    <style>body{width:320px;margin:0;font-family:Inter,system-ui,sans-serif;background:#0f172a;color:white;padding:20px}button{width:100%;border:0;border-radius:12px;background:#3b82f6;color:white;padding:12px;font-weight:700}</style>\n  </head>\n  <body>\n    <h1>${input.popupTitle || safeName}</h1>\n    <p>${input.description || "Your generated Chrome extension popup."}</p>\n    <button id="forge-action">${input.buttonText || "Click me"}</button>\n    <script src="popup.js"></script>\n  </body>\n</html>`,
    "popup.js": `document.getElementById("forge-action").addEventListener("click", () => {\n  const button = document.getElementById("forge-action");\n  button.textContent = "Forged successfully!";\n});\n`
  };
}
